/**
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 * http://www.dspace.org/license/
 */
package uk.ac.ed.datashare.event;

import java.io.File;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import org.apache.logging.log4j.Logger;
import org.dspace.content.Bitstream;
import org.dspace.content.Bundle;
import org.dspace.content.DSpaceObject;
import org.dspace.content.Item;
import org.dspace.content.datashare.DatashareItemDataset;
import org.dspace.content.datashare.service.DatashareDatasetService;
import org.dspace.content.factory.ContentServiceFactory;
import org.dspace.content.service.BitstreamService;
import org.dspace.content.service.ItemService;
import org.dspace.core.Constants;
import org.dspace.core.Context;
import org.dspace.event.Consumer;
import org.dspace.event.Event;
import org.dspace.services.ConfigurationService;
import org.dspace.services.factory.DSpaceServicesFactory;

/**
 * Listens for events raised by DSpace for DataShare and keeps the "download all files" dataset zip
 * in sync with the item, restoring the DataShare 6.x behaviour:
 * <ul>
 *   <li><b>Create</b> - when a new item is installed (archived), generate its dataset zip
 *       immediately so it is downloadable straight away (rather than only after the next
 *       {@code ds-datasets} batch run).</li>
 *   <li><b>Delete on removal</b> - when an item is removed from its collection, delete its dataset
 *       zip (and database record).</li>
 *   <li><b>Delete on fileset change</b> - when a bitstream is added to or removed from one of the
 *       bundles packaged into the zip, the existing zip becomes stale, so delete it (and its
 *       record) so that it is regenerated from the current files by the {@code ds-datasets} job.
 *       The zip is deliberately not regenerated here because the fileset is mid-edit.</li>
 *   <li><b>Reconcile on availability change</b> - the dataset zip is a static file served with no
 *       per-request authorization, so it must only exist on disk while the item's files may be
 *       downloaded: the item is archived, not under embargo, not withdrawn, and the whole access
 *       path (the item, each zip bundle and every bitstream) is readable by Anonymous. When the item
 *       is withdrawn, reinstated, its embargo changes, or a <b>resource policy of one of its files
 *       or zip bundles changes</b> (restricted to / released from a group), reconcile the zip's
 *       existence with that rule: delete it when the content becomes non-public, (re)generate it
 *       when it becomes public again.</li>
 * </ul>
 */
public class DatashareConsumer implements Consumer {

    /**
     * log4j logger
     */
    private static Logger log = org.apache.logging.log4j.LogManager.getLogger(DatashareConsumer.class);

    /**
     * Bundles whose bitstreams are packaged into the dataset zip. Changes to any other bundle
     * (e.g. THUMBNAIL or TEXT generated by media filters) must not trigger a regeneration.
     */
    private static final Set<String> ZIP_BUNDLES = Set.of("ORIGINAL", "CC-LICENSE", "LICENSE");

    private ItemService itemService = ContentServiceFactory.getInstance().getItemService();

    private BitstreamService bitstreamService = ContentServiceFactory.getInstance().getBitstreamService();

    private DatashareDatasetService datasetService =
            ContentServiceFactory.getInstance().getDatashareDatasetService();

    private ConfigurationService configurationService =
            DSpaceServicesFactory.getInstance().getConfigurationService();

    /** Items whose dataset zip must be (re)generated at the end of the current event batch. */
    private Set<UUID> itemsToCreate;

    /** Items whose stale dataset zip must be deleted at the end of the current event batch. */
    private Set<UUID> itemsToDelete;

    /**
     * Items whose availability may have changed (withdraw/reinstate/embargo) and whose zip must
     * therefore be reconciled - created or deleted - against the current availability.
     */
    private Set<UUID> itemsToReconcile;

    @Override
    public void initialize() throws Exception {
        // nothing to initialise
    }

    @Override
    public void consume(Context ctx, Event event) throws Exception {
        // The DataShare zip feature is only active when datasets.path is configured. When it is not,
        // do no work at all (no event resolution, no DB lookups) so that, although this consumer is
        // in the default dispatcher list, it is a true no-op unless the feature is configured.
        String datasetsPath = configurationService.getProperty("datasets.path");
        if (datasetsPath == null || datasetsPath.isEmpty()) {
            return;
        }
        // Only react to operations that run with authorization enforced. The "download all" zip
        // mirrors what an Anonymous user may download, so it is (re)generated for real, access-checked
        // operations (a workflow archive, a resource-policy change). A context that ignores
        // authorization is an internal/system operation (e.g. test object builders, batch import,
        // maintenance) whose item may not be in its final, access-controlled state yet; generating a
        // zip there would be premature, so skip it (the ds-datasets job / a later real event covers it).
        if (ctx.ignoreAuthorization()) {
            return;
        }
        if (itemsToCreate == null) {
            itemsToCreate = new HashSet<>();
        }
        if (itemsToDelete == null) {
            itemsToDelete = new HashSet<>();
        }
        if (itemsToReconcile == null) {
            itemsToReconcile = new HashSet<>();
        }
        try {
            // A new item was installed (archived): generate its zip immediately.
            if (event.getEventType() == Event.INSTALL && event.getSubjectType() == Constants.ITEM) {
                itemsToCreate.add(event.getSubjectID());
                return;
            }
            // An item was removed from its collection: delete its (now orphaned) zip.
            Item removed = resolveItemRemovedFromCollection(ctx, event);
            if (removed != null) {
                itemsToDelete.add(removed.getID());
                return;
            }
            // The item's availability may have flipped (withdraw/reinstate fire MODIFY with a
            // WITHDRAW/REINSTATE detail; an embargo change fires MODIFY_METADATA): reconcile later.
            if (isAvailabilityChange(event)) {
                itemsToReconcile.add(event.getSubjectID());
                return;
            }
            // A resource policy of one of the item's files changed (fires MODIFY on the
            // bitstream/bundle): the files may have become non-public or public again - reconcile.
            Item policyChanged = resolveItemWhosePolicyChanged(ctx, event);
            if (policyChanged != null) {
                itemsToReconcile.add(policyChanged.getID());
                return;
            }
            // A bitstream/bundle that is part of the zip changed: delete the stale zip.
            Item changed = resolveItemWhoseFilesetChanged(ctx, event);
            if (changed != null && changed.isArchived()) {
                itemsToDelete.add(changed.getID());
            }
        } catch (Exception ex) {
            // Never let a problem resolving the event break the operation that produced it.
            log.warn("DatashareConsumer: could not process event " + event, ex);
        }
    }

    /**
     * Whether the event is one that can change an item's availability (and therefore whether its
     * dataset zip should exist): a withdraw/reinstate (Item MODIFY with a WITHDRAW/REINSTATE
     * detail) or an embargo metadata change (Item MODIFY_METADATA).
     *
     * @param event the event being consumed
     * @return {@code true} if the zip's existence may need reconciling
     */
    private boolean isAvailabilityChange(Event event) {
        if (event.getSubjectType() != Constants.ITEM) {
            return false;
        }
        if (event.getEventType() == Event.MODIFY_METADATA) {
            return true;
        }
        return event.getEventType() == Event.MODIFY
                && ("WITHDRAW".equals(event.getDetail()) || "REINSTATE".equals(event.getDetail()));
    }

    /**
     * Work out, for a resource-policy change, the item whose files were affected, or {@code null}
     * when the event is not a relevant policy change. Changing the resource policy of a bitstream or
     * of a zip bundle fires a MODIFY on that bitstream/bundle (from
     * {@code ResourcePolicyService#update}/{@code #delete}); the owning item's zip then needs
     * reconciling because the content may have become non-public (restricted) or public again.
     *
     * @param ctx   DSpace context
     * @param event the event being consumed
     * @return the owning item, or {@code null}
     * @throws Exception if the subject of the event cannot be resolved
     */
    private Item resolveItemWhosePolicyChanged(Context ctx, Event event) throws Exception {
        if (event.getEventType() != Event.MODIFY) {
            return null;
        }
        if (event.getSubjectType() == Constants.BITSTREAM) {
            DSpaceObject subject = event.getSubject(ctx);
            if (subject instanceof Bitstream) {
                DSpaceObject parent = bitstreamService.getParentObject(ctx, (Bitstream) subject);
                if (parent instanceof Item) {
                    return (Item) parent;
                }
            }
        } else if (event.getSubjectType() == Constants.BUNDLE) {
            DSpaceObject subject = event.getSubject(ctx);
            if (subject instanceof Bundle) {
                return firstItem((Bundle) subject);
            }
        }
        return null;
    }

    /**
     * Work out, for a Collection Remove event, the item that was removed from the collection, or
     * {@code null} when the event is not an item-removed-from-collection event.
     *
     * @param ctx   DSpace context
     * @param event the event being consumed
     * @return the removed item, or {@code null}
     * @throws Exception if the object of the event cannot be resolved
     */
    private Item resolveItemRemovedFromCollection(Context ctx, Event event) throws Exception {
        if (event.getEventType() == Event.REMOVE && event.getSubjectType() == Constants.COLLECTION
                && event.getObjectType() == Constants.ITEM) {
            DSpaceObject object = event.getObject(ctx);
            if (object instanceof Item) {
                return (Item) object;
            }
        }
        return null;
    }

    /**
     * Work out, for an Add/Remove event, the item whose fileset changed, or {@code null} when the
     * event is not a relevant fileset change.
     *
     * @param ctx   DSpace context
     * @param event the event being consumed
     * @return the affected item, or {@code null}
     * @throws Exception if the subject/object of the event cannot be resolved
     */
    private Item resolveItemWhoseFilesetChanged(Context ctx, Event event) throws Exception {
        if (event.getEventType() != Event.ADD && event.getEventType() != Event.REMOVE) {
            return null;
        }
        if (event.getSubjectType() == Constants.BUNDLE) {
            // A bitstream was added to / removed from a bundle (subject = bundle).
            DSpaceObject subject = event.getSubject(ctx);
            if (subject instanceof Bundle && isZipBundle(((Bundle) subject).getName())) {
                return firstItem((Bundle) subject);
            }
        } else if (event.getSubjectType() == Constants.ITEM && event.getObjectType() == Constants.BUNDLE) {
            // A whole bundle was added to / removed from the item (subject = item, object = bundle).
            // On removal the bundle may already be gone (object == null); refresh conservatively.
            DSpaceObject object = event.getObject(ctx);
            if (object == null || (object instanceof Bundle && isZipBundle(((Bundle) object).getName()))) {
                DSpaceObject subject = event.getSubject(ctx);
                if (subject instanceof Item) {
                    return (Item) subject;
                }
            }
        }
        return null;
    }

    private boolean isZipBundle(String bundleName) {
        return bundleName != null && ZIP_BUNDLES.contains(bundleName);
    }

    private Item firstItem(Bundle bundle) {
        for (Item item : bundle.getItems()) {
            if (item != null) {
                return item;
            }
        }
        return null;
    }

    @Override
    public void end(Context ctx) throws Exception {
        Set<UUID> toDelete = itemsToDelete;
        Set<UUID> toCreate = itemsToCreate;
        Set<UUID> toReconcile = itemsToReconcile;
        itemsToDelete = null;
        itemsToCreate = null;
        itemsToReconcile = null;

        boolean nothingToDelete = toDelete == null || toDelete.isEmpty();
        boolean nothingToCreate = toCreate == null || toCreate.isEmpty();
        boolean nothingToReconcile = toReconcile == null || toReconcile.isEmpty();
        if (nothingToDelete && nothingToCreate && nothingToReconcile) {
            return;
        }
        // Only do anything when the DataShare zip feature is configured.
        String datasetsPath = configurationService.getProperty("datasets.path");
        if (datasetsPath == null || datasetsPath.isEmpty()) {
            return;
        }
        try {
            // Delete first: if an item was both installed and had files added in the same batch,
            // the create below produces the final, fresh zip.
            if (!nothingToDelete) {
                for (UUID itemId : toDelete) {
                    Item item = itemService.find(ctx, itemId);
                    if (item != null) {
                        datasetService.deleteDatasetForItem(ctx, item);
                    }
                }
            }
            if (!nothingToCreate) {
                for (UUID itemId : toCreate) {
                    Item item = itemService.find(ctx, itemId);
                    if (item != null) {
                        datasetService.createDatasetForItem(ctx, item);
                    }
                }
            }
            if (!nothingToReconcile) {
                for (UUID itemId : toReconcile) {
                    reconcileDatasetZip(ctx, itemService.find(ctx, itemId));
                }
            }
        } catch (Exception ex) {
            log.warn("DatashareConsumer: failed to refresh dataset zip(s)", ex);
        }
    }

    /**
     * Reconcile the existence of an item's dataset zip with whether its files may currently be
     * downloaded. The zip must exist only while the item is archived and its files are available
     * (not embargoed, not withdrawn, and all zip bitstreams readable by Anonymous): generate it when
     * it should exist but does not, delete it when it exists but should not. A no-op when it matches.
     *
     * @param ctx  DSpace context
     * @param item the item to reconcile; ignored when {@code null}, not archived or without a handle
     */
    private void reconcileDatasetZip(Context ctx, Item item) {
        if (item == null || item.getHandle() == null) {
            return;
        }
        // areAllItemBitstreamsAvailable is the single existence rule (archived, not embargoed, not
        // withdrawn, whole access path readable by Anonymous), so a withdrawn/restricted item or a
        // non-archived workspace item is correctly treated as "should not exist".
        boolean shouldExist = DatashareItemDataset.areAllItemBitstreamsAvailable(ctx, item);
        boolean exists = datasetZipExists(item);
        if (shouldExist && !exists) {
            datasetService.createDatasetForItem(ctx, item);
        } else if (!shouldExist && exists) {
            datasetService.deleteDatasetForItem(ctx, item);
        }
    }

    /**
     * Whether the physical dataset zip file currently exists on disk for the given item.
     *
     * @param item the item whose zip file is checked
     * @return {@code true} if the zip file exists, {@code false} otherwise (including on error)
     */
    private boolean datasetZipExists(Item item) {
        try {
            return new File(DatashareItemDataset.getFullFilePath(item.getHandle())).exists();
        } catch (Exception e) {
            return false;
        }
    }

    @Override
    public void finish(Context ctx) throws Exception {
        // nothing to finish
    }
}
