/**
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 * http://www.dspace.org/license/
 */
package uk.ac.ed.datashare.event;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import org.apache.logging.log4j.Logger;
import org.dspace.content.Bundle;
import org.dspace.content.DSpaceObject;
import org.dspace.content.Item;
import org.dspace.content.datashare.service.DatashareDatasetService;
import org.dspace.content.factory.ContentServiceFactory;
import org.dspace.content.service.ItemService;
import org.dspace.core.Constants;
import org.dspace.core.Context;
import org.dspace.event.Consumer;
import org.dspace.event.Event;
import org.dspace.services.ConfigurationService;
import org.dspace.services.factory.DSpaceServicesFactory;

/**
 * Listens for events raised by DSpace for DataShare.
 * <p>
 * When an item's fileset changes - a bitstream is added to or removed from one of the bundles that
 * are packaged into the "download all files" zip - the existing dataset zip becomes stale. This
 * consumer deletes that zip (and its database record) so that it is regenerated from the current
 * files by the {@code ds-datasets} job, mirroring the DataShare 6.x behaviour.
 */
public class DatashareConsumer implements Consumer {

    /**
     * log4j logger
     */
    private static Logger log = org.apache.logging.log4j.LogManager.getLogger(DatashareConsumer.class);

    /**
     * Bundles whose bitstreams are packaged into the dataset zip. Changes to any other bundle
     * (e.g. THUMBNAIL or TEXT generated by media filters) must not trigger a regeneration.
     */
    private static final Set<String> ZIP_BUNDLES = Set.of("ORIGINAL", "CC-LICENSE", "LICENSE");

    private ItemService itemService = ContentServiceFactory.getInstance().getItemService();

    private DatashareDatasetService datasetService =
            ContentServiceFactory.getInstance().getDatashareDatasetService();

    private ConfigurationService configurationService =
            DSpaceServicesFactory.getInstance().getConfigurationService();

    /** Items whose dataset zip must be refreshed at the end of the current event batch. */
    private Set<UUID> itemsToRefresh;

    @Override
    public void initialize() throws Exception {
        // nothing to initialise
    }

    @Override
    public void consume(Context ctx, Event event) throws Exception {
        if (itemsToRefresh == null) {
            itemsToRefresh = new HashSet<>();
        }
        try {
            Item item = resolveItemWhoseFilesetChanged(ctx, event);
            if (item != null && item.isArchived()) {
                itemsToRefresh.add(item.getID());
            }
        } catch (Exception ex) {
            // Never let a problem resolving the event break the operation that produced it.
            log.warn("DatashareConsumer: could not process event " + event, ex);
        }
    }

    /**
     * Work out, for an Add/Remove event, the item whose fileset changed, or {@code null} when the
     * event is not a relevant fileset change.
     *
     * @param ctx   DSpace context
     * @param event the event being consumed
     * @return the affected item, or {@code null}
     * @throws Exception if the subject/object of the event cannot be resolved
     */
    private Item resolveItemWhoseFilesetChanged(Context ctx, Event event) throws Exception {
        if (event.getEventType() != Event.ADD && event.getEventType() != Event.REMOVE) {
            return null;
        }
        if (event.getSubjectType() == Constants.BUNDLE) {
            // A bitstream was added to / removed from a bundle (subject = bundle).
            DSpaceObject subject = event.getSubject(ctx);
            if (subject instanceof Bundle && isZipBundle(((Bundle) subject).getName())) {
                return firstItem((Bundle) subject);
            }
        } else if (event.getSubjectType() == Constants.ITEM && event.getObjectType() == Constants.BUNDLE) {
            // A whole bundle was added to / removed from the item (subject = item, object = bundle).
            // On removal the bundle may already be gone (object == null); refresh conservatively.
            DSpaceObject object = event.getObject(ctx);
            if (object == null || (object instanceof Bundle && isZipBundle(((Bundle) object).getName()))) {
                DSpaceObject subject = event.getSubject(ctx);
                if (subject instanceof Item) {
                    return (Item) subject;
                }
            }
        }
        return null;
    }

    private boolean isZipBundle(String bundleName) {
        return bundleName != null && ZIP_BUNDLES.contains(bundleName);
    }

    private Item firstItem(Bundle bundle) {
        for (Item item : bundle.getItems()) {
            if (item != null) {
                return item;
            }
        }
        return null;
    }

    @Override
    public void end(Context ctx) throws Exception {
        if (itemsToRefresh == null || itemsToRefresh.isEmpty()) {
            itemsToRefresh = null;
            return;
        }
        try {
            // Only do anything when the DataShare zip feature is configured.
            String datasetsPath = configurationService.getProperty("datasets.path");
            if (datasetsPath != null && !datasetsPath.isEmpty()) {
                for (UUID itemId : itemsToRefresh) {
                    Item item = itemService.find(ctx, itemId);
                    if (item != null) {
                        datasetService.deleteDatasetForItem(ctx, item);
                    }
                }
            }
        } catch (Exception ex) {
            log.warn("DatashareConsumer: failed to refresh dataset zip(s)", ex);
        } finally {
            itemsToRefresh = null;
        }
    }

    @Override
    public void finish(Context ctx) throws Exception {
        // nothing to finish
    }
}
