/**
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 * http://www.dspace.org/license/
 */
package uk.ac.ed.datashare.event;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import org.apache.logging.log4j.Logger;
import org.dspace.content.Bundle;
import org.dspace.content.DSpaceObject;
import org.dspace.content.Item;
import org.dspace.content.datashare.service.DatashareDatasetService;
import org.dspace.content.factory.ContentServiceFactory;
import org.dspace.content.service.ItemService;
import org.dspace.core.Constants;
import org.dspace.core.Context;
import org.dspace.event.Consumer;
import org.dspace.event.Event;
import org.dspace.services.ConfigurationService;
import org.dspace.services.factory.DSpaceServicesFactory;

/**
 * Listens for events raised by DSpace for DataShare and keeps the "download all files" dataset zip
 * in sync with the item, restoring the DataShare 6.x behaviour:
 * <ul>
 *   <li><b>Create</b> - when a new item is installed (archived), generate its dataset zip
 *       immediately so it is downloadable straight away (rather than only after the next
 *       {@code ds-datasets} batch run).</li>
 *   <li><b>Delete on removal</b> - when an item is removed from its collection, delete its dataset
 *       zip (and database record).</li>
 *   <li><b>Delete on fileset change</b> - when a bitstream is added to or removed from one of the
 *       bundles packaged into the zip, the existing zip becomes stale, so delete it (and its
 *       record) so that it is regenerated from the current files by the {@code ds-datasets} job.
 *       The zip is deliberately not regenerated here because the fileset is mid-edit.</li>
 * </ul>
 */
public class DatashareConsumer implements Consumer {

    /**
     * log4j logger
     */
    private static Logger log = org.apache.logging.log4j.LogManager.getLogger(DatashareConsumer.class);

    /**
     * Bundles whose bitstreams are packaged into the dataset zip. Changes to any other bundle
     * (e.g. THUMBNAIL or TEXT generated by media filters) must not trigger a regeneration.
     */
    private static final Set<String> ZIP_BUNDLES = Set.of("ORIGINAL", "CC-LICENSE", "LICENSE");

    private ItemService itemService = ContentServiceFactory.getInstance().getItemService();

    private DatashareDatasetService datasetService =
            ContentServiceFactory.getInstance().getDatashareDatasetService();

    private ConfigurationService configurationService =
            DSpaceServicesFactory.getInstance().getConfigurationService();

    /** Items whose dataset zip must be (re)generated at the end of the current event batch. */
    private Set<UUID> itemsToCreate;

    /** Items whose stale dataset zip must be deleted at the end of the current event batch. */
    private Set<UUID> itemsToDelete;

    @Override
    public void initialize() throws Exception {
        // nothing to initialise
    }

    @Override
    public void consume(Context ctx, Event event) throws Exception {
        if (itemsToCreate == null) {
            itemsToCreate = new HashSet<>();
        }
        if (itemsToDelete == null) {
            itemsToDelete = new HashSet<>();
        }
        try {
            // A new item was installed (archived): generate its zip immediately.
            if (event.getEventType() == Event.INSTALL && event.getSubjectType() == Constants.ITEM) {
                itemsToCreate.add(event.getSubjectID());
                return;
            }
            // An item was removed from its collection: delete its (now orphaned) zip.
            Item removed = resolveItemRemovedFromCollection(ctx, event);
            if (removed != null) {
                itemsToDelete.add(removed.getID());
                return;
            }
            // A bitstream/bundle that is part of the zip changed: delete the stale zip.
            Item changed = resolveItemWhoseFilesetChanged(ctx, event);
            if (changed != null && changed.isArchived()) {
                itemsToDelete.add(changed.getID());
            }
        } catch (Exception ex) {
            // Never let a problem resolving the event break the operation that produced it.
            log.warn("DatashareConsumer: could not process event " + event, ex);
        }
    }

    /**
     * Work out, for a Collection Remove event, the item that was removed from the collection, or
     * {@code null} when the event is not an item-removed-from-collection event.
     *
     * @param ctx   DSpace context
     * @param event the event being consumed
     * @return the removed item, or {@code null}
     * @throws Exception if the object of the event cannot be resolved
     */
    private Item resolveItemRemovedFromCollection(Context ctx, Event event) throws Exception {
        if (event.getEventType() == Event.REMOVE && event.getSubjectType() == Constants.COLLECTION
                && event.getObjectType() == Constants.ITEM) {
            DSpaceObject object = event.getObject(ctx);
            if (object instanceof Item) {
                return (Item) object;
            }
        }
        return null;
    }

    /**
     * Work out, for an Add/Remove event, the item whose fileset changed, or {@code null} when the
     * event is not a relevant fileset change.
     *
     * @param ctx   DSpace context
     * @param event the event being consumed
     * @return the affected item, or {@code null}
     * @throws Exception if the subject/object of the event cannot be resolved
     */
    private Item resolveItemWhoseFilesetChanged(Context ctx, Event event) throws Exception {
        if (event.getEventType() != Event.ADD && event.getEventType() != Event.REMOVE) {
            return null;
        }
        if (event.getSubjectType() == Constants.BUNDLE) {
            // A bitstream was added to / removed from a bundle (subject = bundle).
            DSpaceObject subject = event.getSubject(ctx);
            if (subject instanceof Bundle && isZipBundle(((Bundle) subject).getName())) {
                return firstItem((Bundle) subject);
            }
        } else if (event.getSubjectType() == Constants.ITEM && event.getObjectType() == Constants.BUNDLE) {
            // A whole bundle was added to / removed from the item (subject = item, object = bundle).
            // On removal the bundle may already be gone (object == null); refresh conservatively.
            DSpaceObject object = event.getObject(ctx);
            if (object == null || (object instanceof Bundle && isZipBundle(((Bundle) object).getName()))) {
                DSpaceObject subject = event.getSubject(ctx);
                if (subject instanceof Item) {
                    return (Item) subject;
                }
            }
        }
        return null;
    }

    private boolean isZipBundle(String bundleName) {
        return bundleName != null && ZIP_BUNDLES.contains(bundleName);
    }

    private Item firstItem(Bundle bundle) {
        for (Item item : bundle.getItems()) {
            if (item != null) {
                return item;
            }
        }
        return null;
    }

    @Override
    public void end(Context ctx) throws Exception {
        Set<UUID> toDelete = itemsToDelete;
        Set<UUID> toCreate = itemsToCreate;
        itemsToDelete = null;
        itemsToCreate = null;

        boolean nothingToDelete = toDelete == null || toDelete.isEmpty();
        boolean nothingToCreate = toCreate == null || toCreate.isEmpty();
        if (nothingToDelete && nothingToCreate) {
            return;
        }
        // Only do anything when the DataShare zip feature is configured.
        String datasetsPath = configurationService.getProperty("datasets.path");
        if (datasetsPath == null || datasetsPath.isEmpty()) {
            return;
        }
        try {
            // Delete first: if an item was both installed and had files added in the same batch,
            // the create below produces the final, fresh zip.
            if (!nothingToDelete) {
                for (UUID itemId : toDelete) {
                    Item item = itemService.find(ctx, itemId);
                    if (item != null) {
                        datasetService.deleteDatasetForItem(ctx, item);
                    }
                }
            }
            if (!nothingToCreate) {
                for (UUID itemId : toCreate) {
                    Item item = itemService.find(ctx, itemId);
                    if (item != null) {
                        datasetService.createDatasetForItem(ctx, item);
                    }
                }
            }
        } catch (Exception ex) {
            log.warn("DatashareConsumer: failed to refresh dataset zip(s)", ex);
        }
    }

    @Override
    public void finish(Context ctx) throws Exception {
        // nothing to finish
    }
}
